baseURL = ""
title = "Noobing | With The Noob"
paginate = 5
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "UA-123-45"
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Noobing | With The Noob"
description = "A Simple Blog I write to express my opinions about various stuff"
keywords = [ "Blog", "NoobScience Blog", "NoobScience", "Noobing With The Noob", "noobing with the noob", "noobscience blog" ]
author = "Ishan Joshi"
images = [ "https://pbs.twimg.com/profile_banners/1545036800603062273/1657213370/1080x360" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

  [params.assets]
  favicon = "https://newtoallofthis123.github.io/About/assets/icons/icon_round.ico"
  favicon16x16 = "https://newtoallofthis123.github.io/About/assets/icons/icon_round.ico"
  favicon32x32 = "https://newtoallofthis123.github.io/About/assets/icons/icon_round.ico"
  apple_touch_icon = "https://newtoallofthis123.github.io/About/assets/icons/icon_round.ico"
  safari_pinned_tab = "https://newtoallofthis123.github.io/About/assets/icons/icon_round.ico"

  [params.label]
  text = "Noobing"
  icon = "/apple-touch-icon.png"
  iconHeight = 35

  [params.profileMode]
  enabled = true
  title = "Noobing, With The Noob"
  subtitle = "Tech | Open Source | Opinions"
  imageUrl = "/images/noobscience.png"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Hi there ðŸ‘‹"
  Content = "Welcome to my blog"

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/noobscience1"

  [[params.socialIcons]]
  name = "stackoverflow"
  url = "https://stackoverflow.com/users/16859540/noob-science"

  [[params.socialIcons]]
  name = "instagram"
  url = "https://instagram.com/noobscience123"

  [[params.socialIcons]]
  name = "youtube"
  url = "https://youtube.com/@noobscience1"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/newtoallofthis123"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.editPost]
  URL = "https://github.com/newtoallofthis123/noobing/content"
  Text = "Suggest Changes"
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "example"
name = "example.org"
url = "https://example.org"
weight = 30

[markup.highlight]
noClasses = false